### ISSUE TITLE
The file was not found, because of wrong location and .gitignore file

### ISSUE THREAD

**Issue by CzajekDC** [matthijs110/shopping-cart#2]
#### Problem
In [here](https://github.com/matthijs110/shopping-cart/blob/master/app/Http/Controllers/OrderController.php#L212) you use a custom `js` file that is not available, because it is in a `storage/` folder. The `storage/` folder should be used only for temporary files, cache, sessions, rendered views etc, **not** for the actual code.

#### Solution
I personally would move the file into `resources/assets/scripts/pdf/` and change [this](https://github.com/matthijs110/shopping-cart/blob/master/app/Http/Controllers/OrderController.php#L212) accordingly.

**Comment by matthijs110** [comment]
Good point. Working on it now. What would you do btw?

` mix.scripts(['generate-pdf.js'], 'public/js/generate-pdf.js');` or `mix.copy('resources/assets/js/generate-pdf.js', 'public/js/generate-pdf.js');`

**Comment by CzajekDC** [comment]
Do you even need it in public? I don't think so...

**Comment by matthijs110** [comment]
It can't be found if I don't. See edit inside my last comment.

**Comment by matthijs110** [comment]
nvm. Got it :)

**Comment by CzajekDC** [comment]
:)

**Comment by CzajekDC** [comment]
What you could do is even this: `resource_path('assets/scripts/pdf/generate-pdf.js')`.

By the way, why do you use this custom file, since there is no difference between it and the original? Just for future improvements?

---

Also, my external links doesn't seem to work. :( For example the Semantic UI stylesheet and the logo are not included in the PDF whilst they are in the invoice view itself. It seems like Phantom does not support external assets. Do you know how to solve it?

**Comment by matthijs110** [comment]
Thanks. I couldn't find `resource_path()` in the documentation. Probably missed it. 

---

It should work.. The assets are coming from its original CDN. It works fine for me. Could you try to make a route where you return the `pages.order.invoice` view? Or change the `download()` function to:

```php
public function download($hash)
{
    $order = Order::where('hash', $hash)->first();

    // PDF::useScript(resource_path('assets/js/generate-pdf.js'));

    return view('pages.order.invoice', compact('order'), "order-{$order->id}.pdf");
    } 
```
Inside [OrderController](https://github.com/matthijs110/shopping-cart/blob/786205eabbc61a2b593dc760e9080d3685393e13/app/Http/Controllers/OrderController.php#L204)

**Comment by CzajekDC** [comment]
I did. As I said, the view is rendered properly. Only Phantom cannot somehow manage to include those assets... :/

---

I found it directly in `helpers.php`:
```php
if (! function_exists('resource_path')) {
    /**
     * Get the path to the resources folder.
     *
     * @param  string  $path
     * @return string
     */
    function resource_path($path = '')
    {
        return app()->basePath().DIRECTORY_SEPARATOR.'resources'.($path ? DIRECTORY_SEPARATOR.$path : $path);
    }
}
```

**Comment by matthijs110** [comment]
:/ Just for sure: Are all composer components installed correctly? Does Laravel give any errors? Are the files stored inside the storage folder? (Failed jobs will end there..)

**Comment by CzajekDC** [comment]
- [x] Composer
- [ ] Errors
- [ ] Files stored in a storage folder

What is weird is that I had gotten some files stored in the storage file, but now I don't. Maybe I got them when I was getting an error?

**Comment by matthijs110** [comment]
Yea, when you get an error, the view 'result' will be stored inside the storage folder. Its just a raw output of the html.

**Comment by CzajekDC** [comment]
Yes, I see it now when I forced an error. Hmm, that's weird. Is it working for you? Are you sure you don't have any additional files under `.gitignore` folders?

**Comment by matthijs110** [comment]
It works fine for me.. No additional files. Could you try to make a order at [https://63429dce.ngrok.io/](https://63429dce.ngrok.io/) and download the invoice? **Temporary URL**

**Comment by CzajekDC** [comment]
Well, works perfectly.

I am going to try to share my site...

**Comment by matthijs110** [comment]
Alright. Good to know. Lets dig further 👍

**Comment by CzajekDC** [comment]
Didn't know ngrok is paid :/
Trying to solve it with a workaround.

**Comment by matthijs110** [comment]
If you work on a Mac: use Valet (free and easy). Alex made a [tutorial](https://www.codecourse.com/library/lessons/exposing-your-local-web-server/exposing-your-local-web-server) about using ngrok. I didn't see anything about paying?

**Comment by CzajekDC** [comment]
Custom domains are paid. I have to work on a simple localhost:8000. It is now mapped to a different site. Just a sec.

**Comment by CzajekDC** [comment]
Here is a link: http://a2286f0a.ngrok.io
This is the order I already placed for you: http://a2286f0a.ngrok.io/order/a93ebed5a9d16bc44dc8cbddb841c733d11ebd19757d5a2a6ddb5527dc02a91e

**Comment by CzajekDC** [comment]
Oh, and if you hit http://a2286f0a.ngrok.io/invoice you will get the view itself.

**Comment by matthijs110** [comment]
I just forced an error and looked at the view. As I expected, the assets are loaded as it should. The PDF result from your site is missing those assets as you said. 

Are you running on a different OS? It could be the problem that you need a different [PhantomJS file](http://phantomjs.org/download.html).

**Comment by CzajekDC** [comment]
It doesn't work with and without this line: `PDF::useScript(resource_path('assets/scripts/pdf/generate-pdf.js'));`. If it is not included the regular `vendor` file is used, and it works the same way :/

I also created a custom config file for that and added this:
```php
'command_line_options' => [
    '--local-to-remote-url-access=true',
]
```
based on the API reference.

---

I am working on a Mac, but the site is running on Homestead's Ubuntu. I have an older version of Homestead though. It is 0.4.2 instead of 0.4.4.

**Comment by matthijs110** [comment]
Are you able to (temporary) use Laravel Valet? Or update Homestead? I don't think this *is* the issue, but just to make sure..

**Comment by CzajekDC** [comment]
Your PhantomJS file is for Linux 64x, right?

**Comment by matthijs110** [comment]
The custom one uses Mac OS. Not Linux. Thats what I ment to say with 'different OS'

**Comment by matthijs110** [comment]
Did it work with the Linux version of PhantomJS?

**Comment by CzajekDC** [comment]
I mean, in `vendor` there is:
> This packages ships with the 64 bit linux build.

quoting the Doc Block. And Homestead uses exactly that. BTW, if it was the wrong one, it would result in an error like `this file is not an executable` or something like that. :/

**Comment by CzajekDC** [comment]
I think I am gonna just change the provider to something different, like [this](https://github.com/barryvdh/laravel-snappy) or [this](https://github.com/barryvdh/laravel-dompdf). :(

**Comment by matthijs110** [comment]
:/ Well.. go ahead and try 👍  It will not surprise me if one of those **do** work.

**Comment by CzajekDC** [comment]
**Disclaimer:** I solved it! :)

Ok, so Google didn't help, BUT [a closed issue](https://github.com/danielboendergaard/phantom-pdf/issues/1) on the phantom-pdf repo did!

I turned `--debug=true` and this is what it resulted in:
```
[DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.min.css" 
```

The issue page suggests, to add `--ssl-protocol=tlsv1` flag. And it works! Now the assets are being loaded. Yay!

**Comment by matthijs110** [comment]
o; So I actually have to change `https://` to `http://` ?

**Comment by CzajekDC** [comment]
Hmm. That probably would get rid of the error. I think you should keep it though, since it's always a good idea to use SSL.

Maybe just add a `--ssl-protocol=tlsv1` flag in the config file. It must be `config/phantom-pdf.php`. This is mine:
```php
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Temporary File Path
    |--------------------------------------------------------------------------
    |
    | The temporary file path where html and pdf files are stored.
    |
    */

    'temporary_file_path' => storage_path() . '/pdf',

    /*
    |--------------------------------------------------------------------------
    | Phantom Process Timeout (Seconds)
    |--------------------------------------------------------------------------
    |
    | PhantomJS is being executed in a separate process, here we can specify
    | how long to wait for the process to finish before aborting.
    |
    */

    'timeout' => 10,

    /*
    |--------------------------------------------------------------------------
    | PhantomJS Command Line Options
    |--------------------------------------------------------------------------
    |
    | Add list of wanted command line options for PhantomJS
    | List of available options can be found here:
    | http://phantomjs.org/api/command-line.html
    |
    */

    'command_line_options' => [
        '--ignore-ssl-errors=true',
        '--ssl-protocol=tlsv1',
        // '--debug=true',
        '--local-to-remote-url-access=true',
    ]
];
```

**Comment by matthijs110** [comment]
That file does not exist? Do I need to make one?

**Comment by CzajekDC** [comment]
Yes. It will overwrite the default one. The `php artisan vendor:publish` would normally create it for you, but the package doesn't support `tags` that are in the newer version and it won't.

From the Service Provider:
```php
public function boot()
{
    $this->publishes([
        __DIR__.'/../config/config.php' => config_path('phantom-pdf.php')
    ]);
}
```

**Comment by CzajekDC** [comment]
This is the default one FYI: `vendor/danielboendergaard/phantom-pdf/src/config/config.php`.

```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Temporary File Path
    |--------------------------------------------------------------------------
    |
    | The temporary file path where html and pdf files are stored.
    |
    */

    'temporary_file_path' => storage_path(),

    /*
    |--------------------------------------------------------------------------
    | The url for the base tag
    |--------------------------------------------------------------------------
    |
    | Since the HTML file that is loaded into PhantomJS is loaded from the file system,
    | any relative references to assets will not work. We fix this by adding a base tag
    | to the html file.
    |
    */

    'base_url' => url('/'),

    /*
    |--------------------------------------------------------------------------
    | Phantom Process Timeout (Seconds)
    |--------------------------------------------------------------------------
    |
    | PhantomJS is being executed in a separate process, here we can specify
    | how long to wait for the process to finish before aborting.
    |
    */

    'timeout' => 10,

    /*
    |--------------------------------------------------------------------------
    | PhantomJS Binary Path
    |--------------------------------------------------------------------------
    |
    | The path to the PhantomJS binary. This packages ships with the 64 bit linux build.
    | If you want to use another version, reference it here.
    |
    */

    'binary_path' => __DIR__ . '/../../bin/phantomjs',

    /*
    |--------------------------------------------------------------------------
    | Conversion Script
    |--------------------------------------------------------------------------
    |
    | The script used by PhantomJS to convert the page to PDF. If not set the
    | default script will be used.
    |
    */

    'conversion_script' => null,

    /*
    |--------------------------------------------------------------------------
    | PhantomJS Command Line Options
    |--------------------------------------------------------------------------
    |
    | Add list of wanted command line options for PhantomJS
    | List of available options can be found here:
    | http://phantomjs.org/api/command-line.html
    |
    */

    'command_line_options' => [
        //'--ignore-ssl-errors=true',
        //'--debug=true',
    ]

];
```

**Comment by matthijs110** [comment]
Got it :) Should be fixed now.
