### ISSUE TITLE
Attach existing address to a new customer if it exists already

### ISSUE THREAD

**Issue by matthijs110** [matthijs110/shopping-cart#3]
* Make the a few columns inside the `addresses` table unique.
* When a user gives an Address..
    * Check if it exists.
        * Yes: Attach the Address to the new customer.
        * No: Create a new Address.

**Why?** 
I don't like duplicate rows if it doesn't necessarily needs to be there. I don't see any major security issues for now.

**Please tell me if you do**

The only thing I can think of is checking if an order has (ever) been made on a certain address. Although you won't receive an error saying: "This address already exists.". 

Let me know what you think :)

**Comment by DCzajkowski** [comment]
I think it would be generally cool to make this project the one with login and register functionality. That way users would be distinguishable and the address would belong to them nicely. Of course, guest functionality is a must-have, so I would work on that too.

Unfortunately I don't have time for making this. The worst thing is, that you call a `user` a `Customer` and the `User` model is useless.

Have fun though and I'll make sure to work on this project a little more as soon as I find some spare time to do so. :)

Cheers

**Comment by matthijs110** [comment]
That is a cool feature indeed! Just need to sort it out a bit. Like you said: 
> The worst thing is, that you call a user a Customer and the User model is useless.

I don't want to move too far away from the original Shopping Cart series though. The main reasons for making this are fun and as an example for people who want to make a Laravel version of the series as well. 

Perhaps I could make a new repository for fun purposes :) 

Feel free to commit your idea's! 👍

**Comment by DCzajkowski** [comment]
Yes, a fork is a very good idea!

**Comment by matthijs110** [comment]
There we go :)
https://github.com/matthijs110/shopping-cart-extended
