### ISSUE TITLE
500 (Internal Server Error)

### ISSUE THREAD

**Issue by lebedevstudio** [matthijs110/shopping-cart#4]
Hello! I have a problem. How to solve it? It returns.

GET http://localhost/storelaravel/public/braintree/token 500 (Internal Server Error)

...if I try to click on the link - http://localhost/storelaravel/public/braintree/token , I get an error - Braintree\Configuration::merchantId needs to be set (or accessToken needs to be passed to Braintree\Gateway).

In .env file I have made all the settings

**Comment by matthijs110** [comment]
I think the code either can't access the environment variable or the value is invalid. 

Make sure you changed `.env.example` to `.env`

**Comment by lebedevstudio** [comment]
At first it worked, but then it just stopped work. With config ".env" all right.

[screenshot](https://s32.postimg.org/6azdropmd/Capture.png)

**Comment by matthijs110** [comment]
Can you post a screenshot of your error as well? (Have you installed all composer/node dependencies?)

**Comment by lebedevstudio** [comment]
[first screenshot](https://s31.postimg.org/t9ryactff/Capture+2.png)
[second screenshot](https://s31.postimg.org/s8rpl8cfv/Capture.png)

**Comment by matthijs110** [comment]
Are you running a PHP server? Normally you don't access your Laravel installation by going to `/public`. I don't know how this works on Windows. You need something MAMP or WAMP.

**Comment by DCzajkowski** [comment]
The `/public` part is ok. He just doesn't have a rewrite rule set.

**Comment by matthijs110** [comment]
I don't think it has something to do with the code. It works fine for me.. Have you installed all composer/node dependencies? Just want to know for sure

**Comment by DCzajkowski** [comment]
I just cloned fresh one, connected with my Braintree and everything works fine.

**Comment by DCzajkowski** [comment]
The composer dependencies will be enough. In your `.env` file make sure you have correct APP_URL set. Also, make sure you provided correct credentials for your braintree (from sandbox.braintreegateway.com > Account > My User > View Authorizations)

**Comment by lebedevstudio** [comment]
Hmm, strangely enough, the problem goes away by itself. Thanks guys! @matthijs110 Can I ask one last question? In the file - product.blade.php , this line:

`<a href="{{ route('cart.add', ['slug' => $product->slug, 'quantity' => 1]) }}" class="ui labeled icon button"><i class="add to cart icon"></i>Add to cart</a>`

For example: I have a quantity field and a Add to cart button. By clicking on the Add to cart button, the value from the field should appeared in route.

If I use the form, the answer will be something like this: ../product-coffee?quantity=1

If I change the route.php to this, it's also don't works
`Route::get('/cart/add/{slug}?quantity={quantity}', 'CartController@add')->name('cart.add');`

I tried something like this:
```
<form action="{{ route('cart.add', ['slug' => $product->slug, 'quantity' => quantity]) }}" method="GET">
    <input type="number" name="quantity" value="..some value here...">
    <button type="submit">Add to cart</button>
</form>
```

**Comment by matthijs110** [comment]
Try this:

inside `product.blade.php`:
```blade
<form action="{{ route('cart.add', ['slug' => $product->slug, 'quantity' => 1]) }}" method="GET">
	<input type="number" name="quantity" value="1">
	<button type="submit">Add to cart</button>
</form>
```

Inside `CartController.php`, line 60, replace the add method with:
```php
public function add($slug, $quantity)
    {
    	$product = $this->product->where('slug', $slug)->first();

        if (! $product) {
            return redirect('/');
        }

        $input = request()->input('quantity');
        if (isset ($input)) {
            $quantity = request()->input('quantity');
        }

        try {
            $this->basket->add($product, $quantity);
        } catch(QuantityExceededException $e) {
            return $e->message;
        }

        return redirect(route('cart.index'));
    }
```

Should work. Not sure about small bugs.

**Comment by lebedevstudio** [comment]
Thank you very much for your help! It is working. You can close this issue. +1:
